# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

clone:
  depth: full
pipelines:
  default:
    - step:
        name: Create artifact
        script:
          - tar czfv application.tgz pom.xml src/
        artifacts:
          - application.tgz
    - step:
        name: Deploy to production
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_KEY
              HEROKU_APP_NAME: $HEROKU_DEPLOY
              ZIP_FILE: "application.tgz"