// <auto-generated />
using LAPR5_3DD_019.Models.ClassesDeDominio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAPR5_3DD_019.Migrations
{
    [DbContext(typeof(LAPR5DBContext))]
    [Migration("20191023093602_migrations")]
    partial class migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoOperacao", b1 =>
                        {
                            b1.Property<long>("OperacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Id");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("descricaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.Descricao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "duracaoOperacao", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("hora");

                            b1.Property<int>("min");

                            b1.Property<int>("seg");

                            b1.HasKey("Id");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("duracaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
