// <auto-generated />
using LAPR5_3DD_019.Models.ClassesDeDominio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAPR5_3DD_019.Migrations
{
    [DbContext(typeof(LAPR5DBContext))]
    [Migration("20191023141333_migrationslapr")]
    partial class migrationslapr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LAPR5_3DD_019.Models.LinhaProducao", b =>
                {
                    b.Property<float>("Id");

                    b.HasKey("Id");

                    b.ToTable("LinhasProducao");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Maquina", b =>
                {
                    b.Property<string>("nomeMaquina");

                    b.Property<float?>("LinhaProducaoId");

                    b.Property<float?>("tipoMaquinaId");

                    b.HasKey("nomeMaquina");

                    b.HasIndex("LinhaProducaoId");

                    b.HasIndex("tipoMaquinaId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Produto", b =>
                {
                    b.Property<float>("Id");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.TipoMaquina", b =>
                {
                    b.Property<float>("Id");

                    b.HasKey("Id");

                    b.ToTable("TiposMaquina");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Maquina", b =>
                {
                    b.HasOne("LAPR5_3DD_019.Models.LinhaProducao")
                        .WithMany("maquinas")
                        .HasForeignKey("LinhaProducaoId");

                    b.HasOne("LAPR5_3DD_019.Models.TipoMaquina", "tipoMaquina")
                        .WithMany()
                        .HasForeignKey("tipoMaquinaId");

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.PosicaoNaLinhaProducao", "posicaoLinhaProducao", b1 =>
                        {
                            b1.Property<string>("MaquinanomeMaquina");

                            b1.Property<int>("posicaoNaLinhaProducao");

                            b1.HasKey("MaquinanomeMaquina");

                            b1.ToTable("Maquinas");

                            b1.HasOne("LAPR5_3DD_019.Models.Maquina")
                                .WithOne("posicaoLinhaProducao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.PosicaoNaLinhaProducao", "MaquinanomeMaquina")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "duracaoOperacao", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("hora");

                            b1.Property<int>("min");

                            b1.Property<int>("seg");

                            b1.HasKey("Id");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("duracaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoOperacao", b1 =>
                        {
                            b1.Property<long>("OperacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Id");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("descricaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.Descricao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Produto", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.InfoProduto", "informacaoProduto", b1 =>
                        {
                            b1.Property<float>("ProdutoId");

                            b1.Property<string>("descricaoProduto");

                            b1.Property<string>("nomeProduto");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.HasOne("LAPR5_3DD_019.Models.Produto")
                                .WithOne("informacaoProduto")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.InfoProduto", "ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.TipoMaquina", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoTipoMaquina", b1 =>
                        {
                            b1.Property<float>("TipoMaquinaId");

                            b1.Property<string>("Id");

                            b1.HasKey("TipoMaquinaId");

                            b1.ToTable("TiposMaquina");

                            b1.HasOne("LAPR5_3DD_019.Models.TipoMaquina")
                                .WithOne("descricaoTipoMaquina")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.Descricao", "TipoMaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
