// <auto-generated />
using System;
using LAPR5_3DD_019.Models.ClassesDeDominio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAPR5_3DD_019.Migrations
{
    [DbContext(typeof(LAPR5DBContext))]
    [Migration("20191022153112_mi")]
    partial class mi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricaoOperacaoId");

                    b.Property<long?>("duracaoOperacaoId");

                    b.HasKey("Id");

                    b.HasIndex("descricaoOperacaoId");

                    b.HasIndex("duracaoOperacaoId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.ValueObjects.Descricao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Descricao");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("hora");

                    b.Property<int>("min");

                    b.Property<int>("seg");

                    b.HasKey("Id");

                    b.ToTable("DuracaoOperacao");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.HasOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoOperacao")
                        .WithMany()
                        .HasForeignKey("descricaoOperacaoId");

                    b.HasOne("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "duracaoOperacao")
                        .WithMany()
                        .HasForeignKey("duracaoOperacaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
