// <auto-generated />
using LAPR5_3DD_019.Models.ClassesDeDominio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAPR5_3DD_019.Migrations
{
    [DbContext(typeof(MDFContext))]
    [Migration("20191027190758_migartion")]
    partial class migartion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LAPR5_3DD_019.Associations.LinhaProducaoMaquinas", b =>
                {
                    b.Property<long>("id_maquina");

                    b.Property<long>("id_linhaProducao");

                    b.HasKey("id_maquina", "id_linhaProducao");

                    b.HasIndex("id_linhaProducao");

                    b.ToTable("LinhaProducaoMaquinas");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Associations.TipoMaquinaOperacao", b =>
                {
                    b.Property<long>("id_operacao");

                    b.Property<long>("id_tipoMaquina");

                    b.HasKey("id_operacao", "id_tipoMaquina");

                    b.HasIndex("id_tipoMaquina");

                    b.ToTable("TipoMaquinaOperacao");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.LinhaProducao", b =>
                {
                    b.Property<long>("Id");

                    b.HasKey("Id");

                    b.ToTable("LinhasProducao");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Maquina", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("id_tipoMaquina");

                    b.HasKey("Id");

                    b.HasIndex("id_tipoMaquina");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Produto", b =>
                {
                    b.Property<long>("Id");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.TipoMaquina", b =>
                {
                    b.Property<long>("Id");

                    b.HasKey("Id");

                    b.ToTable("TiposMaquina");
                });

            modelBuilder.Entity("LAPR5_3DD_019.Associations.LinhaProducaoMaquinas", b =>
                {
                    b.HasOne("LAPR5_3DD_019.Models.LinhaProducao", "linhaProducao")
                        .WithMany("maquinas")
                        .HasForeignKey("id_linhaProducao")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LAPR5_3DD_019.Models.Maquina", "maquina")
                        .WithMany("linhasProducao")
                        .HasForeignKey("id_maquina")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LAPR5_3DD_019.Associations.TipoMaquinaOperacao", b =>
                {
                    b.HasOne("LAPR5_3DD_019.Models.Operacao", "operacao")
                        .WithMany("tiposMaquinas")
                        .HasForeignKey("id_operacao")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LAPR5_3DD_019.Models.TipoMaquina", "tipoMaquina")
                        .WithMany("operacoesMaquina")
                        .HasForeignKey("id_tipoMaquina")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Maquina", b =>
                {
                    b.HasOne("LAPR5_3DD_019.Models.TipoMaquina", "tipoMaquina")
                        .WithMany("maquinas")
                        .HasForeignKey("id_tipoMaquina")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.NomeMaquina", "nomeMaquina", b1 =>
                        {
                            b1.Property<long>("MaquinaId");

                            b1.Property<string>("nomeMaquina");

                            b1.HasKey("MaquinaId");

                            b1.ToTable("Maquinas");

                            b1.HasOne("LAPR5_3DD_019.Models.Maquina")
                                .WithOne("nomeMaquina")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.NomeMaquina", "MaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.PosicaoNaLinhaProducao", "posicaoLinhaProducao", b1 =>
                        {
                            b1.Property<long>("MaquinaId");

                            b1.Property<int>("posicaoNaLinhaProducao");

                            b1.HasKey("MaquinaId");

                            b1.ToTable("Maquinas");

                            b1.HasOne("LAPR5_3DD_019.Models.Maquina")
                                .WithOne("posicaoLinhaProducao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.PosicaoNaLinhaProducao", "MaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Operacao", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "duracaoOperacao", b1 =>
                        {
                            b1.Property<long>("OperacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("hora");

                            b1.Property<int>("min");

                            b1.Property<int>("seg");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("duracaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.DuracaoOperacao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoOperacao", b1 =>
                        {
                            b1.Property<long>("OperacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Id");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("LAPR5_3DD_019.Models.Operacao")
                                .WithOne("descricaoOperacao")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.Descricao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.Produto", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.InfoProduto", "informacaoProduto", b1 =>
                        {
                            b1.Property<long>("ProdutoId");

                            b1.Property<string>("descricaoProduto");

                            b1.Property<string>("nomeProduto");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.HasOne("LAPR5_3DD_019.Models.Produto")
                                .WithOne("informacaoProduto")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.InfoProduto", "ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("LAPR5_3DD_019.Models.TipoMaquina", b =>
                {
                    b.OwnsOne("LAPR5_3DD_019.Models.ValueObjects.Descricao", "descricaoTipoMaquina", b1 =>
                        {
                            b1.Property<long>("TipoMaquinaId");

                            b1.Property<string>("Id");

                            b1.HasKey("TipoMaquinaId");

                            b1.ToTable("TiposMaquina");

                            b1.HasOne("LAPR5_3DD_019.Models.TipoMaquina")
                                .WithOne("descricaoTipoMaquina")
                                .HasForeignKey("LAPR5_3DD_019.Models.ValueObjects.Descricao", "TipoMaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
